WebZero/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('artistas/', include('artistas.urls')),
    path('catalogo/', include('catalogo.urls')),
    path('contacto/', include('contacto.urls')),
    path('carro/', include('carro.urls')),
    path('autenticacion/', include('autenticacion.urls')),
    path('', include('webzeroapp.urls')),
]

artistas/urls.py
from django.urls import path

from . import views


urlpatterns = [

    path('', views.artistas, name='Artistas'),


]

autenticacion/urls.py
from django.urls import path

from .views import VRegistro, cerrar_sesion, logear


urlpatterns = [
    path('', VRegistro.as_view(), name='Autenticacion'),
    path('cerrar_sesion', cerrar_sesion, name='cerrar_sesion'),
    path('logear', logear, name='logear'),
]

carro/urls.py
from django.urls import path

from . import views

app_name="carro"

urlpatterns = [
    path('agregar/<int:articulo_id>/', views.agregar_articulo, name='agregar'),
    path('eliminar/<int:articulo_id>/', views.eliminar_articulo, name='eliminar'),
    path('restar/<int:articulo_id>/', views.restar_articulo, name='restar'),
    path('limpiar/', views.limpiar_carro, name='limpiar'),
]

catalogo/urls.py
from django.urls import path

from . import views


urlpatterns = [
    path('', views.catalogo, name='Catalogo'),

]

contacto/urls.py
from django.urls import path

from . import views


urlpatterns = [
    path('', views.contacto, name='Contacto'),

]

webzeroapp/urls.py
from django.urls import path

from webzeroapp import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', views.home, name='Home'),
    path('tienda', views.tienda, name='Tienda'),

]

urlpatterns+=static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT)

artistas/models.py
from django.db import models

# Create your models here.

class Artista (models.Model):
    rut=models.CharField(primary_key=True, max_length=10)
    nombre = models.CharField(max_length=20)
    aPaterno = models.CharField(max_length=20)
    aMaterno = models.CharField(max_length=20)
    fechaNacimiento = models.DateField(blank=False, null=False)
    email= models.EmailField(unique=True, max_length=100, blank=True, null=True) 
    telefono = models.CharField(max_length=45)
    foto = models.ImageField(upload_to='artistas')

def __str__(self):
    return self.nombre

autenticacion/models.py
from django.db import models

# Create your models here.

catalogo/models.py
from django.db import models

from artistas.models import Artista

# Create your models here.

class Categoria(models.Model):
    nombre = models.CharField(max_length=30)
    
    def __str__(self):
        return self.nombre
    
class Articulo(models.Model):
    nombre = models.CharField(max_length=20)
    descripcion = models.CharField(max_length=200)
    foto = models.ImageField(upload_to='catalogo')
    precio = models.IntegerField()
    artista = models.ForeignKey(Artista,on_delete=models.CASCADE,db_column='nombreArtista')
    categoria = models.ForeignKey(Categoria,on_delete=models.CASCADE,db_column='nombreCategoria')

    def __str__(self):
        return self.nombre

contacto/forms.py
from django import forms

class FormularioContacto(forms.Form):
    nombre = forms.CharField(label= "Nombre", max_length=50, required=True)
    email = forms.CharField(label= "Mail" , max_length=50, required=True)
    contenido = forms.CharField(label= "Contenido", widget=forms.Textarea)

artistas/views.py
from django.shortcuts import render
from artistas.models import Artista

# Create your views here.

def artistas(request):
    artistas = Artista.objects.all()

    return render(request, "artistas/artistas.html",{"artistas":artistas}) 

autenticacion/views.py
from django.shortcuts import render, redirect
from django.views.generic import View
from django.contrib.auth import login, logout, authenticate
from django.contrib import messages
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
# Create your views here.

class VRegistro(View):

    def get (self,request):
        form=UserCreationForm()
        return render(request,'registro/registro.html',{'form':form})

    def post(self,request):
        form=UserCreationForm(request.POST)
        if form.is_valid():
            usiario=form.save()
            login(request, usiario)
            return redirect ('Home')
        else:
            for msg in form.error_messages:
                messages.error(request, msg)
            return render(request,'registro/registro.html',{'form':form})

def cerrar_sesion(request):
    logout(request)
    return redirect ('Home')

def logear(request):
    if request.method == 'POST':
        form = AuthenticationForm(request, data=request.POST)
        if form.is_valid():
            nombre_usuario = form.cleaned_data.get('username')
            contra = form.cleaned_data.get('password')
            usuario = authenticate(username=nombre_usuario, password=contra)
            if usuario is not None:
                login(request, usuario)
                return redirect('Home')
            else:
                messages.error(request, 'Usuario o contraseña incorrectos')
        else:
            messages.error(request, 'Usuario o contraseña incorrectos')
    form=AuthenticationForm()
    return render(request,'login/login.html',{'form':form})

    

carro/views.py
from django.shortcuts import render
from .carro import Carro
from catalogo.models import Articulo
from django.shortcuts import redirect

# Create your views here.

def agregar_articulo(request,articulo_id):
    carro=Carro(request)
    articulo=Articulo.objects.get(id=articulo_id)
    carro.agregar(articulo=articulo)
    return redirect ("Catalogo")

def eliminar_articulo(request,articulo_id):
    carro=Carro(request)
    articulo=Articulo.objects.get(id=articulo_id)
    carro.eliminar(articulo=articulo)
    return redirect ("Catalogo")

def restar_articulo(request,articulo_id):
    carro=Carro(request)
    articulo=Articulo.objects.get(id=articulo_id)
    carro.restar_articulo(articulo=articulo)
    return redirect ("Catalogo")

def limpiar_carro(request, articulo_id):
    carro = Carro(request)
    carro.limpiar_carro()
    return redirect ("Catalogo")

catalogo/views.py
from django.shortcuts import render
from .models import Articulo
# Create your views here.

def catalogo(request):
    articulos = Articulo.objects.all()
    return render(request, "catalogo/catalogo.html", {"articulos":articulos})

def catalogo(request):
    if 'carro' not in request.session:
        request.session['carro'] = {}

    articulos = Articulo.objects.all()  # Asumiendo que tienes un modelo llamado Articulo
    return render(request, "catalogo/catalogo.html", {"articulos": articulos})

contacto/views.py
from django.shortcuts import render, redirect
from .forms import FormularioContacto
from django.core.mail import EmailMessage

# Create your views here.

def contacto(request):
    formulario_contacto=FormularioContacto
    if request.method == "POST":
        formulario_contacto=FormularioContacto(data=request.POST)
        if formulario_contacto.is_valid():
            nombre=request.POST.get('nombre')
            email=request.POST.get('email')
            contenido=request.POST.get('contenido')

            email=EmailMessage("Mensaje desde app Django",
                               "El usuario con nombre {} con la dirección {} escribe lo siguiente: \n\n {}".format(nombre,email,contenido),
                               "",["loree.bravo.bremer@gmail.com"], reply_to=[email])
            try:
                email.send()
                return redirect("/contacto/?valido")
            except:
                return redirect("/contacto/?novalido")

    return render(request, "contacto/contacto.html", {'miformulario': formulario_contacto})

webzeroapp/views.py
from django.shortcuts import render

from carro.carro import Carro


# Create your views here.

def home(request):
    carro=Carro(request)

    return render(request, "webzeroapp/home.html")


def tienda(request):

    return render(request, "webzeroapp/tienda.html")

artistas/templates/artistas/artistas.html
<!-- Hola ouh-->

{% extends "webzeroapp/base.html" %}

{% load static %}

{% load bootstrap5 %}

{% bootstrap_css %}

{% bootstrap_javascript %}

{% block content %}

<div class="container mt-4">
    <div class="row">
        {% for artista in artistas %}
        <div class="col-md-4 mb-4">
            <div class="card h-100">
                <img src="{{artista.foto.url}}" class="card-img-top" alt="{{artista.nombre}}">
                <div class="card-body">
                    <h3 class="card-title"><b>{{artista.nombre}} {{artista.aPaterno}}</b></h3>
                    <p class="card-text" style="text-align: center;"> biografía del artista puede ir aqui</p>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>

{% endblock %}

autenticacion/templates/login/login.html
{% extends "webzeroapp/base.html" %}

{% load static %}

{% load bootstrap5 %}

{% bootstrap_css %}

{% bootstrap_javascript %}



{% block content %}

<form method="post" action="" style = "color: white; padding-bottom: 50%;" >
    {% csrf_token %}

    
    <div style="width: 75%; margin: auto; text-align: center;" >
            {% if messages %}
            {% for mensaje in messages %}
            <span class="alert alert-{{mensaje.tags}}">{{mensaje}}</span>
            
            {% endfor %}

            {% endif %}
            <br><br>
        {{form}}
        <button type="submit" class="btn btn-primary">Ingresa</button>
    </div>
</form>
    

{% endblock %}

autenticacion/templates/registro/registro.html
{% extends "webzeroapp/base.html" %}

{% load static %}

{% load bootstrap5 %}

{% bootstrap_css %}

{% bootstrap_javascript %}



{% block content %}
<div class="container mt-5" style="padding-bottom: 15%;">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <div class="card" style="background-color: #333; color: white;">
                <div class="card-header text-center" style="background-color: #555; color: white;">
                    <h4>Registro</h4>
                </div>
                <div class="card-body">
                    <form method="post" action="">
                        {% csrf_token %}
                        {% for field in form %}
                            <div class="mb-3">
                                <label for="{{ field.id_for_label }}" class="form-label">{{ field.label }}</label>
                                {{ field }}
                                {% if field.help_text %}
                                    <div class="form-text" style="color: #ccc;">{{ field.help_text }}</div>
                                {% endif %}
                                {% if field.errors %}
                                    <div class="text-danger">
                                        {% for error in field.errors %}
                                            <div>{{ error }}</div>
                                        {% endfor %}
                                    </div>
                                {% endif %}
                            </div>
                        {% endfor %}
                        <div class="d-grid gap-2">
                            <button type="submit" class="btn btn-secondary" style="background-color: #555; border: none;">Regístrate</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

catalogo/templates/carro/widget.html
<table class ="table table-bordered" style="color: white;">
    <thead>
        <tr>
            <th colspan ="3" class="text-center">Carro de compras</th>
        </tr>
        <tr>
            <th>Producto</th>
            <th>Cantidad</th>
            <th>Suma</th>

        </tr>
    </thead>

    <tbody>
        {% if request.session.carro.items %}
            {% for key, value in request.session.carro.items %}
                <tr class="text-center">
                    <td>{{ value.nombre }}</td>
                    <td>{{ value.cantidad }}</td>
                    <td>
                        {% if value.articulo_id %}
                            <a href="{% url 'carro:agregar' value.articulo_id %}" class="btn btn-sm btn-success">+</a>
                            <a href="{% url 'carro:restar' value.articulo_id %}" class="btn btn-sm btn-success">-</a><br>
                        

                            {{value.precio}} CLP
                        {% endif %}
                    </td>


                </tr>

            {% endfor%}
        {% else %}
            <tr>
                <td colspan="3">
                    <div class="alert alert-danger text-center">
                        Sin productos!
                    </div>
                </td>
            </tr>
        {% endif%}
    </tbody>
    <tfoot>
        <tr>
            <td colspan="3">

                Total: {{importe_total_carro}} CLP
            </td>
        </tr>
    </tfoot>


</table>

catalogo/templates/catalogo/catalogo.html
{% extends "webzeroapp/base.html" %}

{% load static %}

{% load bootstrap5 %}

{% bootstrap_css %}

{% bootstrap_javascript %}

{% block content %}
<div class="container mt-4">
    <div class="row">
        <!-- Carrito -->
        <div class="col-md-4 order-md-2 mb-4">
            <div class="card bg-dark text-dark">
                <div class="card-body">
                    {% if request.user.is_authenticated %}
                        {% include "carro/widget.html" %}
                    {% else %}
                        <div class= "alert alert-danger text-center">Login para ver carro</div>
                    {% endif %}
                </div>
            </div>
        </div>

                <!-- Catálogo -->
                <div class="col-md-8 order-md-1">
                    <div class="row">
                        {% for articulo in articulos %}
                        <div class="col-md-6 col-lg-4 mb-4">
                            <div class="card h-100">
                                <img src="{{articulo.foto.url}}" class="card-img-top img-fluid fixed-img-size" alt="{{articulo.nombre}}">
                                <div class="card-body d-flex flex-column">
                                    <h5 class="card-title">{{articulo.nombre}}</h5>
                                    <p class="card-text">{{articulo.descripcion}}</p>
                                    <p class="card-text mt-auto">{{articulo.precio}} CLP</p>
                                    <a href="{% url 'carro:agregar' articulo.id %}" class="btn btn-primary mt-auto">Agregar al carro</a>
                                </div>
                            </div>
                        </div>
                {% endfor %}
            </div>
        </div>
    </div>
</div>

<style>
    .custom-cart-card {
        background-color: #f8f9fa; /* Color de fondo claro */
        color: #343a40; /* Color de texto oscuro */
    }
    
    .fixed-img-size {
        height: 200px;
        object-fit: cover;
    }
</style>
{% endblock %}

contacto/templates/contacto/contacto.html
{% extends "webzeroapp/base.html" %}

{% load static %}

{% load bootstrap5 %}

{% bootstrap_css %}

{% bootstrap_javascript %}

{% block content %}
<br>
<div style="padding-left: 42%;"><h1 style="font-family: rif; color: whitesmoke;">¡Contáctanos!</h1>
</div>

<br>
<br>

<div style="padding-left: 32%;">
<div style="background-color: beige; width: 30rem; padding: 3%;"><p>¡Nos encantaría saber de usted! Si tiene alguna pregunta, necesita información adicional sobre nuestras obras de arte, o desea hacer una consulta, no dude en ponerse en contacto con nosotros!.</p></div>
</div>

<br>
<br>

<div class="contenedorFormulario" style="display: flex; justify-content: center; gap: 20px; padding-bottom: 1%;">
    
    {% if  "valido" in request.GET %}

    <p style = "color: white;">Mensaje enviado correctamente</p>

    {% endif %}
    <form action="" method="POST" style="text-align: center;">
        {% csrf_token %}
        <table style="color: white; margin: 20px auto;">{{miformulario.as_table}}</table>
        <input type="submit" value="Enviar" class="btn btn-primary">
    </form>
    </div>
</div>

<!-- Contenedor para el mapa -->
<div id="map" style="height: 300px; width: 100%; margin-top: 30px;"></div>

<script>
    function initMap() {
        var location = {lat: -33.015348, lng: -71.550746}; // Coordenadas de ejemplo
        var map = new google.maps.Map(document.getElementById('map'), {
            zoom: 10,
            center: location
        });
        var marker = new google.maps.Marker({
            position: location,
            map: map
        });
    }
    </script>
    

{% endblock %}

webzeroapp/templates/webzeroapp/base.html
<html>

<head>

    {% load static %}

  
     <!-- Cargando Bootstrap CSS y JS (de bootstrap) -->

    {% load bootstrap5 %}

    {% bootstrap_css %}

    {% bootstrap_javascript %}

     <!-- Fonts -->
    
     <link href="https://fonts.googleapis.com/css2?family=Raleway:wght@300&display=swap" rel="stylesheet"> 
     <link href="https://fonts.googleapis.com/css?family=Lora:400,400i,700,700i" rel="stylesheet">
     <!-- Google Maps API -->
    <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyD44mlhC6pUSCQcOmb5AE0_Ja8H8EDbk2w&callback=initMap" async defer></script>
    
     

    <!-- Styles -->
    <link href="{% static 'webzeroapp/css/gestion.css' %}" rel="stylesheet">
</head>

<body>
 <!-- Navbar -->
 <nav class="navbar navbar-expand-lg bg-body-tertiary"style="background-color: #e4e2dd;">
  <div class="container-fluid">
    <a class="navbar-brand" href="#"><img src="{% static 'webzeroapp/img/zero.png' %}" alt="Logo" width="60" height="40" class="d-inline-block align-text-top">
    </a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link" href="{% url 'Home' %}"style="color:  #333;">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'Artistas' %}"style="color:  #333;">Artistas</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'Contacto' %}"style="color:  #333;">Contacto</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'Catalogo' %}"style="color:  #333;">Catalogo</a>
        </li>
      </ul>
    </div>
    <div style="color:  #333;"> 
      {% if user.is_authenticated %}

      Hola!, {{ user.username }}&nbsp;&nbsp;<a href="{% url 'cerrar_sesion' %}"style="color:  #333;">Cerrar sesion</a>

      {% else %}
      <a href="{% url 'logear' %}"style="color:  #333;">Log in</a>&nbsp;&nbsp;<a href="{% url 'Autenticacion' %}"style="color:  #333;">Registrate</a>
      {% endif %}
    </div>
  </div>
</nav>


   <!-- Contenido cambiante -->
   {% block content%}

   {% endblock %}

<!-- Footer -->
<footer style="background-color: #333; color: white; text-align: center; padding: 20px;">

  <p>© 2024 Galería y Café Zero. Todos los derechos reservados.</p>
  <p>Email: info@tuempresa.com | Teléfono: 123-456-789</p>
</footer>


  

  

</body>


</html>

webzeroapp/templates/webzeroapp/home.html
{% extends "webzeroapp/base.html" %}

{% load static %}

{% load bootstrap5 %}

{% bootstrap_css %}

{% bootstrap_javascript %}

{% block content %}

   <!-- carrusel -->
   <div id="carouselExampleIndicators" class="carousel slide">
    <div class="carousel-indicators">
      <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
      <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="1" aria-label="Slide 2"></button>
      <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="2" aria-label="Slide 3"></button>
    </div>
    <div class="carousel-inner">
      <div class="carousel-item active" style="max-height: 500px;">
        <img src="{% static 'webzeroapp/img/escultura-madera3.jpg' %}" class="d-block w-100" alt="Escultura Madera">
      </div>
      <div class="carousel-item" style="max-height: 500px;">
        <img src="{% static 'webzeroapp/img/valerie-hadida-sculpture2.jpg' %}" class="d-block w-100" alt="Esculturas Jose">
      </div>
      <div class="carousel-item" style="max-height: 500px;">
        <img src="{% static 'webzeroapp/img/angeles.jpg'  %}" class="d-block w-100" alt="Pintura">
      </div>
    </div>
    <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Previous</span>
    </button>
    <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Next</span>
    </button>
  </div>
<div>
<p></p>
<p></p>
</div>
<div class="container mt-4">
  <div class="row">
    <div class="col-md-4 mb-4">
        <div class="card h-100">
            <img src="{% static 'webzeroapp/img/acuarela_arte.jpg' %}" class="card-img-top" alt="Imagen 1">
            <div class="card-body">
                <h4 class="card-title" style="background-color: aliceblue;">Acuarela</h4>
                <p class="card-text" style="color: rgb(92, 144, 189)">Descripción</p>
            </div>
        </div>
    </div>
    <div class="col-md-4 mb-4">
        <div class="card h-100">
            <img src="{% static 'webzeroapp/img/barcoacua.jpg' %}" class="card-img-top" alt="Imagen 2">
            <div class="card-body">
                <h4 class="card-title" style="background-color: aliceblue;">Acuarela</h4>
                <p class="card-text" style="color: rgb(92, 144, 189);">Descripción</p>
            </div>
        </div>
    </div>
    <div class="col-md-4 mb-4">
        <div class="card h-100">
            <img src="{% static 'webzeroapp/img/wcolor1.jpg' %}" class="card-img-top" alt="Imagen 3">
            <div class="card-body">
                <h4 class="card-title" style="background-color: aliceblue;">Acuarela</h4>
                <p class="card-text" style="color: rgb(92, 144, 189)">Descripción</p>
            </div>
        </div>
    </div>
  </div>
  
  <div class="d-flex justify-content-center mt-4">
    <button class="btn btn-primary">Ver más</button>
  </div>
</div>
  
    <!-- Message -->
    <section class="page-section cta" style="background-color: transparent;">
      <div class="container">
        <div class="row">
          <div class="col-xl-9 mx-auto">
            <div class="cta-inner text-center rounded">
              <h2 class="section-heading mb-4">
                <span class="section-heading-upper">Compromiso total</span>
                <span class="section-heading-lower">Garantizado</span>
              </h2>
              <p class="mb-0">Con más de 75 años de experiencia, en nuestra galería de arte tenemos los conocimientos y herramientas necesarios para llevar cualquier obra de arte a la puerta de su casa con puntualidad y profesionalismo.</p>
            </div>
          </div>
        </div>
      </div>
    </section>

    {% endblock %}
   

    

webzeroapp/templates/webzeroapp/tienda.html
{% extends "webzeroapp/base.html" %}

{% load static %}

{% block content %}

<div><p></p></div>

{% endblock %}